# Generated by Django 3.2.3 on 2021-05-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_category', models.CharField(max_length=200)),
                ('bg_content', models.CharField(max_length=255)),
            ],
        ),
    ]
