# Generated by Django 3.2.3 on 2021-05-19 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0002_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(help_text='Enter unique genre', max_length=100, unique=True)),
                ('cat_description', models.CharField(default='', help_text='A description of the genre', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='bg_author',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='bg_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='bg_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='bg_upload_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogs',
            name='bg_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogAPI.category'),
        ),
    ]
