# Generated by Django 3.2.3 on 2021-05-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0003_auto_20210519_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='bg_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
