# Generated by Django 3.2.3 on 2021-05-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0004_alter_blogs_bg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='bg_content',
            field=models.TextField(),
        ),
    ]
