# Generated by Django 3.2.3 on 2021-07-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0005_alter_blogs_bg_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='bg_img',
            field=models.CharField(max_length=200),
        ),
    ]
