# Generated by Django 3.2.3 on 2021-07-06 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0007_alter_blogs_bg_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='bg_img',
        ),
        migrations.AddField(
            model_name='blogs',
            name='bg_img_url',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
